version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
